library(data.table)
library(plyr)
train <- fread("/media/3TB/kag/salesforecast/input/train.csv")
train_item_store_unique <- unique(train[,c("item_nbr","store_nbr"),with=FALSE])
test <- fread("/media/3TB/kag/salesforecast/input/test.csv")
test_item_store_unique <- unique(test[,c("item_nbr","store_nbr"),with=FALSE])
items <- fread("/media/3TB/kag/salesforecast/input/items.csv")
stores <- fread("/media/3TB/kag/salesforecast/input/stores.csv")
train_item_store_unique <- merge(train_item_store_unique,items,by = "item_nbr")
train_item_store_unique <- merge(train_item_store_unique,stores,by = "store_nbr")
test_item_store_uniques_dt <- merge(test_item_store_unique,train_item_store_unique,by=c("store_nbr","item_nbr"),all.x = TRUE)
#train_family_store_unique <- train_item_store_unique[!duplicated(train_item_store_unique[,c("store_nbr","family"),with=F])]
train_family_store_unique <- ddply(train_item_store_unique,c("store_nbr","family"),head,1)
test_item_city_uniques_dt <- ddply(train_item_store_unique,c("item_nbr","city"),head,1)